[[mods]]
modId = "pennywisemod"
version = "${file.jarVersion}"
displayName = "Pennywise Mod"
credits = "bd3194345"
authors = "bd3194345"
description = '''A mod where players transform into Pennywise.'''

[[dependencies.pennywisemod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pennywisemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
